### ISSUE TITLE
Category "updates" is reserved.

### ISSUE THREAD

**Issue by npalix** [mikalhart/ESP32-OTA-Pull#7]
ArduinoIDE raises the following message:
`WARNING: Category 'updates' in library ESP32-OTA-Pull is not valid. Setting to 'Uncategorized'`

The properties should be updated.
https://github.com/mikalhart/ESP32-OTA-Pull/blob/2b35fde29712f7b5322983e6744916473be85c3f/library.properties#L7

I propose to use either "OTA" or "FUOTA".

**Comment by npalix** [comment]
After a bit more investigation, the category field is limited to some enumeration.

Interesting values are : "Communication", "Other", and "Uncategorized".
For sake of similarity, "Communication" is better.
https://github.com/arduino-libraries/Arduino_ESP32_OTA/blob/main/library.properties

**Comment by mikalhart** [comment]
Done.  Thanks for the tip @npalix
